spring.application.name=library-management-system

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/library_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false

logging.level.root=INFO
logging.level.com.kshitiz.librarymanagementsystem=INFO

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

openai.api.key=${OPENAI_API_KEY:}
openai.model=gpt-3.5-turbo

app.super-admin-email=${SUPER_ADMIN_EMAIL:leader@gmail.com}
payment.upi.id=${PAYMENT_UPI_ID:your-upi-id@bank}